In [5]:
import numpy as np
X = [[1, 2, 3], [4, -4, 5], [5, 6, 7]]
np.ones(6) / 6


array([0.16666667, 0.16666667, 0.16666667, 0.16666667, 0.16666667,
       0.16666667])

In [5]:
X = [['bnjj'], ['vghcvg'], ['fsdgg'], ['dfgdfg'], ['dfgdfg'], ['dfgdfg']]
for i, row in enumerate(X):
    print(f"Row {i}: {row}")

Row 0: ['bnjj']
Row 1: ['vghcvg']
Row 2: ['fsdgg']
Row 3: ['dfgdfg']
Row 4: ['dfgdfg']
Row 5: ['dfgdfg']


In [13]:
eigenvalues, eigenvectors = np.linalg.eig(np.cov(X, rowvar=False))
print(eigenvectors)
sorted_idx = np.argsort(eigenvalues)[::-1]
eigenvalues = eigenvalues[sorted_idx]
eigenvectors[:, sorted_idx]


[[-0.66208471  0.74343912 -0.09456272]
 [-0.08276059 -0.19793858 -0.97671439]
 [ 0.7448453   0.6388416  -0.19257957]]


array([[-0.09456272,  0.74343912, -0.66208471],
       [-0.97671439, -0.19793858, -0.08276059],
       [-0.19257957,  0.6388416 ,  0.7448453 ]])

In [11]:
eigenvectors[:, :2]

array([[-0.09456272,  0.74343912],
       [-0.97671439, -0.19793858],
       [-0.19257957,  0.6388416 ]])